### PR TITLE
Start setting up some unit tests and the download functionality (incomplete)

### PR DESCRIPTION
**Pull request by NutterzUK**

### CODE REVIEW

**Comment by Chaosmi** [comment]
Had a quick look in the car, nice work man. Liking the unit tests. What do you think to having a set of integration tests that call the actual api to verify nothing has changed etc? Maybe there could be a some setting we twiddle that makes our unit tests hit the mocked server or the actual server or just have a different set of tests? I wouldn't be too concerned with testing the actual response from the server, just that it works and we can parse it etc, otherwise it might just become a set of unit tests for the api and not just testing our code :)

**Comment by NutterzUK** [comment]
:). I think that's a good idea. My only concern would be the build failing if the API goes down or if it can't be reached for any reason. I just added travis too so now the github page should show test coverage etc.

**Comment by NutterzUK** [comment]
I also commited some stuff directly into master earlier.. i'll not do that again :+1:

**Comment by Chaosmi** [comment]
Cool, maybe i could add something that just checks for success responses and would be more of a warning than a test failure,

**Comment by Chaosmi** [comment]
Also travis is cool

**Comment by Chaosmi** [comment]
Are you waiting on me to merge this in or do you still have more to add? :)

**Comment by NutterzUK** [comment]
Either - I don't mind :). I'm struggling to download the files which are
uploaded at the moment. I haven't added anything else.

**Pull request merged**
